
pull_request_rules:
  - name: automatic merge
    conditions:
#      - label!=DNM
      - '#approved-reviews-by>=1'
      - 'status-success=ci/circleci'
      - 'base=master'
      - 'label!=work-in-progress'
    actions:
      merge:
        method: merge
        strict: smart
      dismiss_reviews: {}
      delete_head_branch: {}