---
# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# pre-commit install --hook-type commit-msg
#
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: 'https://github.com/commitizen-tools/commitizen'
    rev: v2.17.4
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: 'https://github.com/jorisroovers/gitlint'
    rev: bf0df47
    hooks:
      - id: gitlint
