version: "3"
services:
  cropmanager:
    image: tsobu/spring-cropmanager:latest
    hostname: spring-cropmanager
    container_name: spring-cropmanager
    restart: always
    ports:
      - 8098:8098