
#FROM openjdk:16-slim-buster
FROM eclipse-temurin:17-jre

LABEL maintainer="barsamms@gmail.com"

COPY migrations/build/libs/migrations-*.jar migration-app.jar

ENTRYPOINT ["java", "-jar", "migration-app.jar"]
