version: "3.3"
services:
  api:
    image: iita/akilimo-service:${IMAGE_TAG}
    container_name: akilimo-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8098:8098
    environment:
      SPRING_PROFILES_ACTIVE: uat
      DB_URL: "jdbc:mariadb://db:3306/akilimo"
      DB_USER: akilimo
      DB_PASS: akilimo

  migration:
    image: iita/akilimo-service-migration:${IMAGE_TAG}
    container_name: akilimo-migration
    build:
      context: .
      dockerfile: Dockerfile.migration
    restart: on-failure
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:mariadb://db:3306/akilimo"
      DB_USER: akilimo
      DB_PASS: akilimo

  db:
    container_name: db
    image: bitnami/mariadb:10.9
    restart: "on-failure"
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: akilimo
      MARIADB_DATABASE: akilimo
      MARIADB_USER: akilimo
      MARIADB_PASSWORD: akilimo
