debug: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
  config: file:src/main/resources/logback-spring.xml
server:
  port: 8098
  #servlet:
  #  context-path: /api/v2/recommendations
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: cropmanager
  profiles:
    active: dev
  liquibase:
    change-log: "classpath:liquibase/master.xml"

plumber:
  fertilizer-recommendation: http://localhost:8000/api/v2/dst/fertilizer-recommendation
  planting-practices: http://localhost:8000/api/v2/dst/fertilizer-recommendation
  intercropping: http://localhost:8000/api/v2/dst/fertilizer-recommendation
  scheduled-planting: http://localhost:8000/api/v2/dst/fertilizer-recommendation
  high-starch: http://localhost:8000/api/v2/dst/fertilizer-recommendation