---
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8098
spring:
  application:
    name: cropmanager
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://192.168.100.4:3306/cropmanager"
    username: kodi
    password: kodi
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    change-log: "classpath:liquibase/master.xml"
  profiles:
    active: uat