debug: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
  config: file:src/main/resources/logback-spring.xml
server:
  port: 8098
  #servlet:
  #  context-path: /api/v2/recommendations
  #error:
  #  whitelabel:
  #    enabled: false
spring:
  application:
    name: akilimo
  profiles:
    active: dev
  liquibase:
    change-log: "classpath:liquibase/master.xml"

akilimo:
  currency:
    ngn-usd-rate: 360
    tzs-usd-rate: 2250
    kes-usd-rate: 103
plumber:
  base-url: http://142.93.160.27:8000/api/ #http://localhost:8000/api/
  recommendation-ng: v2/dst/recommendation/ng/compute
  recommendation-tz: v2/dst/recommendation/tz/compute
  recommendation-ng-demo: v2/dst/recommendation/demo/ng/compute
  recommendation-tz-demo: v2/dst/recommendation/demo/tz/compute
  demo-mode: false

messaging:
  test-numbers:
  web-hook-url: https://enj4dfsqm8xr.x.pipedream.net
  plivo:
    end-point: https://api.plivo.com/v1/Account
    auth-id:
    auth-key:
    sender:
  infobip:
    end-point:
    user-name:
    user-pass:
    auth-key:
    sender:
  email:
    sender:
    pass:

