debug: false
trace: false

logging:
  level:
    org:
      hibernate:
        SQL: error
  config: file:src/main/resources/logback-spring.xml
server:
  port: 8098
  error:
    whitelabel:
      enabled: true
    include-stacktrace: on_trace_param
spring:
  application:
    name: akilimo
  profiles:
    active: cmd
  http:
    log-request-details: false
  liquibase:
    change-log: "classpath:liquibase/master.xml"

akilimo:
  currency:
    ngn-usd-rate: 360
    tzs-usd-rate: 2250
    kes-usd-rate: 103
plumber:
  demo-mode: false
  base-url: http://localhost:8000/api/
  recommendation-ng: v2/dst/recommendation/ng/compute
  recommendation-tz: v2/dst/recommendation/tz/compute
  recommendation-ng-demo: v2/dst/recommendation/demo/ng/compute
  recommendation-tz-demo: v2/dst/recommendation/demo/tz/compute

messaging:
  test-numbers:
  web-hook-url: https://enj4dfsqm8xr.x.pipedream.net
  plivo:
    end-point: https://api.plivo.com/v1/Account
    auth-id:
    auth-key:
    sender:
  infobip:
    end-point:
    user-name:
    user-pass:
    auth-key:
    sender:
  email:
    sender:
    pass:

