version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Tests and check coverage
          command: ./gradlew check
      - run: ./gradlew build

      - run:
          name: Build application Docker image
          command: |
            docker build -t iita/acai-akilimo-api:$CIRCLE_SHA1 .
      - run:
          name: Save application Docker image
          command: |
            mkdir /tmp/workspace
            docker save -o /tmp/workspace/image.tar iita/acai-akilimo-api:$CIRCLE_SHA1
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /tmp

          paths:
            - workspace
  push_latest:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load application Docker image
          command: |
            docker load --input /tmp/workspace/image.tar
      - run:
          name: Tag docker image
          command: |
            docker tag iita/acai-akilimo-api:$CIRCLE_SHA1 iita/acai-akilimo-api:latest
      - run:
          name: Push customer feedback Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push iita/acai-akilimo-api:latest
  push_production:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load application Docker image
          command: |
            docker load --input /tmp/workspace/image.tar
      - run:
          name: Tag docker image
          command: |
            docker tag iita/acai-akilimo-api:$CIRCLE_SHA1 iita/acai-akilimo-api:production
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push iita/acai-akilimo-api:production
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push_latest:
          filters:
            branches:
              only:
                - develop
          requires:
            - build
      - push_production:
          filters:
            branches:
              only:
                - master
          requires:
            - build