debug: ${akilimo.dev-mode}
trace: ${akilimo.dev-mode}

server:
  port: ${PORT_NUMBER:8098}
  error:
    whitelabel:
      enabled: false

spring:
  main:
    banner-mode: console
    log-startup-info: true


  application:
    name: akilimo-api

  jmx:
    enabled: ${JMX_ENABLED:false}
  jdbc:
    template:
      fetch-size: 50
  jpa:
    properties:
      hibernate:
        dialect: ${DIALECT:org.hibernate.dialect.MySQLDialect}
        generate_statistics: ${GEN_STATS:false}
        order_inserts: true
        order_updates: true
        ddl-auto: validate
        jdbc:
          batch_size: 5

    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/akilimo}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 50

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss


springdoc:
  show-actuator: true
  default-produces-media-type: "application/json"
  pathsToMatch: /api/**/**
  api-docs:
    path: /akilimo-api
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
#    operations-sorter: alpha

rate:
  limit:
    enabled: ${RATE_ENABLED:false}
    rate-type: ${RATE_TYPE:minute}
    max-request: ${MAX_REQUESTS:1}

akilimo:
  dev-mode: ${DEV_MODE:false}
  name: 'AKILIMO API'
  version: '4.0.0'
  desc: 'Description here'
  externaldoc: ${akilimo.version}
  license: 'GPL'
  license_url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'

  developer:
    name: ${DEV_NAME:Akilimo Team}
    email: ${DEV_NAME:akilimo@cgiar.org}
    url: ${DEV_NAME:akilimo.org}

  ona:
    csv-path: ${OUTPUT_PATH:D:\\dev\\python\\ona-download\\downloads\\converted\\}

  currency:
    ngn-usd: ${NGN_USD:360}
    ghs-usd: ${GHS_USD:6.11}
    tzs-usd: ${TZS_USD:2250}
    kes-usd: ${KES_USD:108}

  plumber:
    base-url: ${PLUMBER_BASE:http://akilimo.prod:8090/api/}
    compute-ng: ${COMPUTE_NG:v2/dst/recommendation/ng/compute}
    compute-tz: ${COMPUTE_TZ:v2/dst/recommendation/tz/compute}
    compute-gh: ${COMPUTE_GH:v2/dst/recommendation/gh/compute}
    compute-rw: ${COMPUTE_RW:v2/dst/recommendation/rw/compute}

  messaging:
    sms:
      base-url: ${SMS_BASE_URL:https://api.tsobu.co.ke}
      end-point: ${SMS_ENDPOINT:/v1/sms/single}
      sms-user: ${SMS_USER:}
      sms-pass: ${SMS_PASS:}
      sms-token: ${SMS_TOKEN:}
      branded-codes: [ "255","+255","234","+234" ]
    email:
      sender: ${EMAIL_SENDER:}
      pass: ${EMAIL_PASS:}

  recommendation: # Hold default values for recommendations for each country
    username: ${spring.application.name}
    user-field: ${akilimo.recommendation.username}
    user-phone-code: NA
    user-phone-number: NA
    user-email: NA
    cmp: 0
    fcy: 0
    risk-att: 0
    pd-window: 0
    hd-window: 0
    fallow-type: bush
    fallow-height: 100
    fallow-green: true
    problem-weeds: false
    tractor-plough: false
    sms: false
    email: false
    tractor-harrow: false
    tractor-ridger: false
    name-sf: NA
    sale-sf: false
    ploughing: false
    ridging: false
    method-ploughing: NA
    method-ridging: NA
    method-harrowing: NA
    cost-lmo-area-basis: areaUnit
    cass-pd: roots
    maize-pd: fresh_cob
    cass-up-m1: 0
    cass-up-m2: 0
    cass-up-p1: 0
    cass-up-p2: 0
    sweet-potato-uw: 0
    sweet-potato-up: 0
    cass-up: 0
    cass-uw: 0
    maize-up: 0
    maize-uw: 0
    cost-manual-ploughing: 0
    cost-manual-harrowing: 0
    cost-manual-ridging: 0
    cost-tractor-ploughing: 0
    cost-tractor-harrowing: 0
    cost-tractor-ridging: 0
    cost-weeding1: 0
    cost-weeding2: 0
    max-inv: 0
