server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    hibernate:
      ddl-auto: none
