debug: false
trace: false

logging:
  level:
    org:
      hibernate:
        SQL: error
  config: file:src/main/resources/logback-spring.xml
server:
  port: 8098
  error:
    whitelabel:
      enabled: true
    include-stacktrace: on_trace_param
spring:
  application:
    name: akilimo
  profiles:
    active: dev
  http:
    log-request-details: false
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 500
  data:
    web:
      pageable:
        one-indexed-parameters: true
rate:
  limit:
    enabled: false
    rate-type: minute
    max-request: 1

akilimo:
  currency:
    ngn-usd-rate: 360
    tzs-usd-rate: 2250
    kes-usd-rate: 103
plumber:
  demo-mode: false
  base-url: http://compute-prod:8000/api/
  dev-url: http://compute-dev:8001/api/
  recommendation-ng: v2/dst/recommendation/ng/compute
  recommendation-tz: v2/dst/recommendation/tz/compute
  recommendation-ng-demo: v2/dst/recommendation/demo/ng/compute
  recommendation-tz-demo: v2/dst/recommendation/demo/tz/compute

messaging:
  sms:
    branded-codes: ["255","+255","234","+234"]
    base-url: https://api.tsobu.co.ke
    end-point: /v1/sms/single
    sms-user:
    sms-token:
  email:
    sender:
    pass:
