debug: ${DEBUG:false}
trace: ${TRACE:false}

spring:
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/master.xml"

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/akilimo}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  #    hikari:
  #      connection-timeout: 20000
  #      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
