debug: ${DEBUG:false}
trace: ${TRACE:false}

spring:
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/master.xml"
    clear-checksums: ${CLEAR_CHECKSUM:false}
    rollback-file: log/akilimo.rollback.sql

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/akilimo_db}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
        generate_statistics: true
