spring:
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/master.xml"

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/akilimo}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
