debug: ${DEBUG:false}
trace: ${TRACE:false}

spring:
  liquibase:
    enabled: ${MIGRATION_ENABLED:false}
    change-log: "classpath:/liquibase/master.xml"
    rollback-file: log/akilimo.rollback.sql
#    database-change-log-table: fuelrod_migration
#    database-change-log-lock-table: fuelrod_migration_lock
    clear-checksums: ${CLEAR_CHECKSUM:false}

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/akilimo_db}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
        generate_statistics: true
