name: Create issues from todos
on:
  push:
    branches:
      - master

jobs:

  todos:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Todo Actions
        uses: dtinth/todo-actions@master
