name: Create issues from todos
on:
  push:
    branches:
      - develop

jobs:

  todos:
    name: Run TODO generator
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Todo Actions
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          LABEL: "todo"
          INCLUDE_PATTERN: "\\.(java|kt|kts)$"
